### ISSUE TITLE
when refresh static file ( such as image ) multi times, nodejs will throw this error..how to resolve it..

### ISSUE THREAD

**Issue by KELEN** [pkoretic/koa-static-server#1]
{ [Error: write ECANCELED]
  code: 'ECANCELED',
  errno: 'ECANCELED',
  syscall: 'write',
  address: undefined }
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

  Error: read ECONNRESET
      at exports._errnoException (util.js:856:11)
      at TCP.onread (net.js:544:26)

**Comment by pkoretic** [comment]
Hi Kelen.

Whicn nodejs version are you using?
i will try to reproduce this to see where is the error.

**Comment by KELEN** [comment]
hello, i'm test nodejs latest version or 0.12.4 also come with this error, you can test with a big image and refresh the browser by F5 all the time to see if it happen..i'm put my website to remote server which system is linux, the probability of this happen is bigger..it seem to happen because of the big file..
thank.my english is bad..

**Comment by pkoretic** [comment]
Sorry for the late response
I think this should be solved with latest koa-send that is now upgraded
please reopen if it still persists, however this is definitely something on their side
