### ISSUE TITLE
koa-static-server can't be put in front of koa-router

### ISSUE THREAD

**Issue by xiongyechang** [pkoretic/koa-static-server#17]
I found a bug in koa-static-router

```javascript
const server = require("koa-static-server");
const { PostRoute } = require("./routes");

// tag-1
app.use(server({
  rootDir: path.join(process.cwd(), "src", "public")
}));
// tag-1

// tag-2
app.use(PostRoute.routes()).use(PostRoute.allowedMethods());
// tag-2
```
look this code, When I send a get request, the HTTP response is 404,
but when I swap tag-1 and tag-2, the HTTP response is 200

**Comment by xiongyechang** [comment]
Because koa-static-server intercepted koa-router

**Comment by pkoretic** [comment]
Hi @xiongyechang 
that is default behavior, as stated in [readme](https://github.com/pkoretic/koa-static-server#options), you can use **last** option
**last** {boolean} don't execute any downstream middleware. defaults to true
