### ISSUE TITLE
1.5.0 breaks serving filenames with spaces (or probably any type of URL encoding)

### ISSUE THREAD

**Issue by rj33** [pkoretic/koa-static-server#20]
This commit :
https://github.com/pkoretic/koa-static-server/commit/8e254e48ae7279e3cdc796f606e6f93aad1e3a67

Has broken file serving for paths with spaces in them.

The commit added this code:

let CurrentPath = join(opts.rootDir, path); 
const stat = await fs.stat(CurrentPath);

At this point paths with spaces will still be URL encoded i.e. a path like:
dir/file with space.jpg
will actually be:
dir/file%20with%20space.jpg

These filenames previously worked because koa-send was doing a 
decodeURLComponent on the path, and nothing before then was trying to doing anything to
path as a file, but now the fs.stat does, and it fails with a ENOENT error and the file isn't served.

Changing it to the following worked for me:
        let CurrentPath = join(opts.rootDir, path);
        CurrentPath = decodeURIComponent(CurrentPath);
        const stat = await fs.stat(CurrentPath);

But you might want to do some error checking on the deocdeURIComponent call.

This is probably a fairly urgent problem , as it means anyone upgrading to 1.5.0 will suddenly find any filename on a path requiring URL encoding will suddenly be failing to serve.

**Comment by pkoretic** [comment]
Hi @rj33, thanks a lot for this report
I have to reverify that commit and also check https://github.com/pkoretic/koa-static-server/pull/19

**Comment by pkoretic** [comment]
@rj33 could you check latest master - https://github.com/pkoretic/koa-static-server/commit/0731aef0004bfeafb527db48b79d44e8a41ec0f1
this code shouldn't be there, if you don't use forbidden option you will get 404 on folders which is good

**Comment by rj33** [comment]
Thanks for the quick response. The version in master fixes the erroring on a non-decoded URI encoded path for me.  I don't use default directory files, so I can't confirm that works, but I am getting 404s on raw folder accesss as expected, so the no index path seems to be working as expected. It would be great if you could push an npm release when you're ready. Close this report whenever you're ready.

**Comment by pkoretic** [comment]
Thanks again for reporting. 1.5.1 is out with this fix!
