### ISSUE TITLE
Changing rootPath per call

### ISSUE THREAD

**Issue by tzookb** [pkoretic/koa-static-server#22]
Hey 👋 

I’m serving my sites from two diff domains:

- example.com
- other.com/site/folder/

How do I make sure my static files will be served properly?

Because whatever version i tried it only supported one of the two each time

Thanks!

**Comment by pkoretic** [comment]
Hi @tzookb 
I believe you can just create two different middlewares ?

app.use(serve({rootDir: 'web'}))
app.use(serve({rootDir: site/folder', rootPath: '/web'}))

you might also want to use `last: false` with the first route

**Comment by tzookb** [comment]
Nice
I’ll surely try it out.
My current hack I did is adding a middleware that remove the extra path from the url
