### ISSUE TITLE
Pass instead of 404

### ISSUE THREAD

**Issue by Diokuz** [pkoretic/koa-static-server#5]
It is better to pass request to the next middleware, if file not exists. I have multiple directories, and also webpack-dev-server, and I want to combine them all. But `koa-static-server` stops all requests.

**Comment by pkoretic** [comment]
Fine by me, I'll do it asap.

**Comment by pkoretic** [comment]
Actually, this is all done by koa-send dependency which throws in that case - https://github.com/koajs/send/blob/master/index.js#L115

The usage is the same as with the other static servers, you can write something along these lines
```
try {
  await next()
}
catch(e) { 
   ... if error is enonent do something else
}
not pretty but I would have to do a similar thing, would that suffice?

**Comment by Diokuz** [comment]
Okay, thanks.
