### ISSUE TITLE
Should it only respond to GET requests?

### ISSUE THREAD

**Issue by vjpr** [pkoretic/koa-static-server#9]
I have a POST request on the same path, and the file server is handling it instead of the POST handler.

**Comment by pkoretic** [comment]
Hi @vjpr
You are right, it should only handle GET and HEAD requests, thanks for this

this should be added before try and await send
``` if (ctx.method === 'HEAD' || ctx.method === 'GET') {```

give me some time to test, if you have it tested I will accept pull request,
thanks

**Comment by pkoretic** [comment]
Published as 1.3.3!
